# Generated by Django 4.2.7 on 2025-03-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('manzil', models.TextField()),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Karta orqali')], default='naqd', max_length=20)),
                ('holat', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlangan', 'Tasdiqlangan'), ('yuborilgan', 'Yuborilgan'), ('yetkazilgan', 'Yetkazilgan'), ('bekor_qilingan', 'Bekor qilingan')], default='kutilmoqda', max_length=20)),
                ('jami_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('foydalanuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='kategoriyalar/')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsif', models.TextField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chegirma_narx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rasm', models.ImageField(upload_to='maxsulotlar/')),
                ('mavjud', models.BooleanField(default=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('miqdor', models.PositiveIntegerField(default=0)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulotlar', to='asosiy.kategoriya')),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessiya_id', models.CharField(blank=True, max_length=100, null=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_ismi', models.CharField(blank=True, max_length=100, null=True)),
                ('jami_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Karta orqali')], default='naqd', max_length=20)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('kassir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savdolar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
            },
        ),
        migrations.CreateModel(
            name='SavdoMaxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.maxsulot')),
                ('savdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savdo_maxsulotlari', to='asosiy.savdo')),
            ],
            options={
                'verbose_name': 'Savdo maxsuloti',
                'verbose_name_plural': 'Savdo maxsulotlari',
            },
        ),
        migrations.CreateModel(
            name='SavatMaxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.maxsulot')),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savatlar', to='asosiy.savat')),
            ],
            options={
                'verbose_name': 'Savat maxsuloti',
                'verbose_name_plural': 'Savat maxsulotlari',
            },
        ),
        migrations.CreateModel(
            name='OmborHarakati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harakat_turi', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('inventarizatsiya', 'Inventarizatsiya')], max_length=20)),
                ('miqdor', models.IntegerField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omborharakatlari', to='asosiy.maxsulot')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
            },
        ),
        migrations.CreateModel(
            name='BuyurtmaMaxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtma_maxsulotlari', to='asosiy.buyurtma')),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.maxsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma maxsuloti',
                'verbose_name_plural': 'Buyurtma maxsulotlari',
            },
        ),
    ]
